apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-api-logs-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /D/kubernetes/backend-api/logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-api-files-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /D/kubernetes/backend-api/files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-api-logs-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-api-files-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi