version: '3'

services: 
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: wk
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: wk
    links:
      - mongo
  mongo:
    image: mongo:3.4.9
    restart: always
    container_name: mongo
    command: 
      - --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: wk
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
networks:
  default:
volumes:
  mongo:
