apiVersion: apps/v1 
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2   
      maxUnavailable: 0  
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - image: backend
          name: backend-api
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: backend-api-port
          env:
            - name: DB_HOST
              value: mongo-db
          livenessProbe:
            httpGet:
              path: /system/healthcheck
              port: backend-api-port
            initialDelaySeconds: 15
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /system/healthcheck
              port: backend-api-port
            initialDelaySeconds: 15
            timeoutSeconds: 30
          volumeMounts:
            - mountPath: /app/logs
              name: backend-api-logs
            - mountPath: /app/src/public
              name: backend-api-files
      volumes:
        - name: backend-api-logs
          persistentVolumeClaim:
            claimName: backend-api-logs-pvc
        - name: backend-api-files
          persistentVolumeClaim:
            claimName: backend-api-files-pvc
            