apiVersion: v1
kind: Service
metadata:
  name: backend-api
spec:
  ports:
  - port: 3000
    nodePort: 31030
    targetPort: backend-api-port
    protocol: TCP
  selector:
    app: backend-api
  type: NodePort