apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  ports:
    - port: 27017
      targetPort: mongo-db-port
      protocol: TCP
      nodePort: 31017
  selector:
    app: mongo-db
  # clusterIP: None
  type: NodePort